FROM rust:1.89-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config cmake iproute2 ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["sleep", "infinity"]
