#!/bin/bash
# Generate auth keys and JWT tokens for moq-multicam.
# Run once before `docker compose up`.
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AUTH_DIR="$SCRIPT_DIR/auth"
ENV_FILE="$SCRIPT_DIR/.env"
GEN_TOKEN="$SCRIPT_DIR/scripts/gen-token/target/release/moq-gen-token"

# Build gen-token if needed
if [ ! -f "$GEN_TOKEN" ]; then
  echo "Building gen-token..."
  (cd "$SCRIPT_DIR/scripts/gen-token" && cargo build --release --quiet)
fi

# Generate keys if needed
if [ ! -f "$AUTH_DIR/server.jwk" ]; then
  echo "Generating ES256 key pair..."
  "$GEN_TOKEN" keygen --output-dir "$AUTH_DIR"
else
  echo "Keys already exist in $AUTH_DIR"
fi

# Generate publisher token (publish + subscribe all paths, 1 year)
PUBLISHER_JWT=$("$GEN_TOKEN" token --key "$AUTH_DIR/server.jwk" --publish "")
echo "Generated publisher JWT"

# Generate operator token (publish control + subscribe all, 1 year)
OPERATOR_JWT=$("$GEN_TOKEN" token --key "$AUTH_DIR/server.jwk" --publish "vehicle/")
echo "Generated operator JWT"

# Write .env
cat > "$ENV_FILE" <<EOF
# Generated by setup-auth.sh — do not commit
MOQ_JWT=$PUBLISHER_JWT
MOQ_OPERATOR_JWT=$OPERATOR_JWT
EOF
chmod 600 "$ENV_FILE"

echo ""
echo "Written to $ENV_FILE:"
echo "  MOQ_JWT          (publisher — full publish + subscribe)"
echo "  MOQ_OPERATOR_JWT (operator — publish vehicle/*/control + subscribe)"
echo ""
echo "Usage:"
echo "  docker compose up                    # publisher uses MOQ_JWT from .env"
echo "  http://localhost:5173/?jwt=\$MOQ_OPERATOR_JWT  # operator viewer"
echo "  http://localhost:5173/               # anonymous viewer (subscribe only)"
